GET http://localhost:3001/api/gifts

###
DELETE http://localhost:3001/api/gifts/61f2dfde98009d387ce7a9fd

###

POST http://localhost:3001/api/gifts HTTP/1.1
content-type: application/json

{
  "gift": "Chocolate",
  "quantity": 1, 
  "price": 1234,
  "owner": "Irma"
}
### 
PUT http://localhost:3001/api/gifts/61e706d59a7bca9d20cccda5 HTTP/1.1
content-type: application/json

{
  "gift": "Pelota",
  "quantity": 1, 
  "price": 5678,
  "owner": "Norma"
}